name: gesture-controller
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
    - mediapipe==0.10.14
    - opencv-python==4.10.0.84
    - tensorflow
    - pyautogui
    - pystray
    - pycaw
    - comtypes
